name: film_match_backend
description: Backend server for Film Match application
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.5
  mongo_dart: ^0.9.1
  dotenv: ^4.2.0
  json_annotation: ^4.8.1
  firebase_admin: ^0.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1 